apiVersion: v1
kind: Service
metadata:
    labels:
        app: myapp
    name: myapp-svc
spec:
    ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
    selector:
        app: myapp
    #type: ClusterIP